language: python
python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
install: python setup.py install
script: py.test
env:
  global:
    secure: ZrJWkjx1n9HHzI7tGStE1akvvZ7uTdFONci6uEJaL+RpHFdi1Vl8Xh1smrBbghgdaBbQbjHJ21fEoxdqtPHHRlbB83YnawkZjKldkPlzOsA1ELQ8QIEKYCl3mAyzIIBzYL/UIqT+NTnosXkAZkTN0kGU3VqR+q3u+I4Jum/bks8=
